(package "vs-edit-mode"
         "0.1.0"
         "Minor mode accomplish editing experience in Visual Studio")

(website-url "https://github.com/emacs-vs/vs-edit-mode")
(keywords "convenience" "editing" "vs")

(package-file "vs-edit-mode.el")

(source "gnu")
(source "jcs-elpa")
(source "melpa")

(depends-on "emacs" "26.1")
(depends-on "ts-fold")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
